spring:
  profiles:
    active: dev
# Swagger Defination   
swagger:
  apis: /cc/*
  description: Cash Control
  developer:
    contact: anandk@triconinfotech.com
  license:
    url: http://triconinfotech.com
  service:
    url: http://triconinfotech.com
  title: Cash Control
  version: '1.0'    
    
---
# All Dev Enviorment configuration and Constants
spring:
  profiles: dev
  

  
    
---
# All Test Enviorment configuration and Constants
spring:
  profiles: test
  
  
---
# All Non-prod Enviorment configuration and Constants
spring:
  profiles: non-prod
  
  
---
# All Prod Enviorment configuration and Constants
spring:
  profiles: prod